### ISSUE TITLE
 Network Policy Enforcement

### ISSUE THREAD

**Issue by afritzler** [ironcore-dev/ironcore-net#275]
## Overview

The `ironcore-net` project currently lacks a mechanism for enforcing network policies. This feature request aims to develop a network policy concept derived from the network policy object in the generic `ironcore` projects. Implementing network policy enforcement will enhance the security and management of network traffic within the `ironcore-net` project.

## Goals

1. **Define the Ironcore-Net Policy Object**: We need to establish how the network policy object specific to `ironcore-net` will be structured, considering its derivation from the generic `ironcore` network policy object.
   
2. **Extend the NetworkInterface in Ironcore-Net**: The `NetworkInterface` in `ironcore-net` must be extended to reflect the effective policies for a network interface. These policies should be mapped by the `metalnetlet` to the `firewallrules` field in the `metalnet` NetworkInterface (`NIC`) type.

3. **Controller Logic for Policy and NIC Mapping**: Define the controller logic that will handle the mapping between a policy and a Network Interface Card (NIC) on which the policy should be enforced.

### 1. Ironcore-Net Policy Object

- **Task**: Define the structure and fields of the `ironcore-net` policy object, considering its compatibility and derivation from the generic `ironcore` network policy object.
- **Acceptance Criteria**:
  - The policy object must include fields that specify both ingress and egress rules.
  - It should support specifying protocols, ports, and IP ranges for both ingress and egress traffic.
  - Compatibility with the generic `ironcore` network policy object must be ensured.

### 2. Extending the NetworkInterface

- **Task**: Design and implement the extension of the `NetworkInterface` in `ironcore-net` to include effective policy enforcement details.
- **Acceptance Criteria**:
  - The `NetworkInterface` must have a new field or structure to hold `firewallrules` as mapped by the `metalnetlet`.
  - The extension must ensure that policies can be effectively applied and represented in the `metalnet` NIC type.

### 3. Controller Logic for Policy-NIC Mapping

- **Task**: Develop the controller logic that will map network policies to NICs for enforcement.
- **Acceptance Criteria**:
  - The controller must accurately map network policies to the appropriate NICs based on the policy definitions.
  - It should watch for changes in network policies and update NIC firewall rules accordingly.
  - The logic must support the dynamic application of policies to NICs without requiring a restart of the network interface or the node.

## Implementation Steps

1. **Research and Analysis**: Review the current `ironcore-net` and `ironcore` projects to understand the existing network policy structure and its application.
2. **Design Phase**:
   - Design the `ironcore-net` specific policy object.
   - Propose extensions to the `NetworkInterface`.
   - Outline the controller logic for policy-NIC mapping.
3. **Development and Testing**: Implement the proposed designs, followed by thorough testing to ensure reliability and security.
4. **Documentation**: Update the `ironcore-net` documentation to include the new network policy enforcement features, usage examples, and configuration guidelines.

## Out of Scope

- Modifying the underlying network model or infrastructure outside the scope of network policy enforcement.
- Integration with external network policy management tools or platforms.

**Comment by Rohit-0505** [comment]
### Here is the sample `networkpolicy.yaml`  for `ironcore-net`

``` yaml
apiVersion: core.apinet.ironcore.dev/v1alpha1
kind: NetworkPolicy
metadata:
  namespace: default
  # networkpolicy-uid is the uid of corresponding networkpolicy in ironcore cluster
  name: networpolicy-uid
spec:
  # This specifies the target network to limit the traffic in.
  networkRef:
  # network-uid is the ironcore-net cluster's network name which refers to corresponding network's uid in ironcore cluster
    name: network-uid
  # Only network interfaces in the specified network will be selected.
  networkInterfaceSelector:
     matchLabels:
       app: db
  # If the policy types are not specified, they are inferred on whether
  # any ingress / egress rule exists. If no ingress / egress rule exists,
  # the network policy is denied on admission.
  policyTypes:
  - Ingress
  - Egress
  # Multiple ingress / egress rules are possible.
  ingress:
  - from:
    # Traffic can be limited from a source IP block.
    - ipBlock:
        cidr: 172.17.0.0/16
    # Traffic can also be limited to objects of the networking api.
    # For instance, to limit traffic from network interfaces, one could
    # specify the following:
    - objectSelector:
        kind: NetworkInterface
        matchLabels:
          app: web
    # Analogous to network interfaces, it is also possible to limit
    # traffic coming from load balancers:
    - objectSelector:
        kind: LoadBalancer
        matchLabels:
          app: web
    # Ports always have to be specified. Only traffic matching the ports
    # will be allowed.
    ports:
    - protocol: TCP
      port: 5432
    - protocol: UDP
      port: 223
  egress:
  - to:
    - ipBlock:
        cidr: 10.0.0.0/24
    ports:
    - protocol: TCP
      port: 8080
```
