### ISSUE TITLE
`apinetlet` creates malformatted labels for IPv6 `VirtualIPs`

### ISSUE THREAD

**Issue by afritzler** [ironcore-dev/ironcore-net#322]
**Describe the bug**

When creating a `VirtualIP` to allocate an IPv6 IP address we are currently having a bug in the `apinetlet` were it tries to create a malformatted label:

Example manifest:
```
apiVersion: networking.ironcore.dev/v1alpha1
kind: VirtualIP
metadata:
  name: foo
spec:
  type: Public
  ipFamily: IPv6
```

Error output:

```
labels: Invalid value: \"2a10:afc0:e013:c000:4a2d:f71f:32e:ca45\": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')"}
```
