### ISSUE TITLE
when creating the `Loadbalancer` resource the apinetlet should have an optional instruction to inject node affinity alongside the anti affinity

### ISSUE THREAD

**Issue by balpert89** [ironcore-dev/ironcore-net#413]
# Summary

Currently, the apinetlet does not populate the [`.spec.template.spec.affinity.nodeAffinity` field](https://github.com/ironcore-dev/ironcore-net/blob/main/api/core/v1alpha1/instance_types.go#L48) when it applies the api-net `Loadbalancer` object [in the loadbalancer controller](https://github.com/ironcore-dev/ironcore-net/blob/main/apinetlet/controllers/loadbalancer_controller.go#L308).

The idea is to populate the node affinity based on the nodes the controller [already identifies based on the api LoadbalancerRouting](https://github.com/ironcore-dev/ironcore-net/blob/main/apinetlet/controllers/loadbalancer_controller.go#L184).

## Basic example

Given this `LoadbalancerRouting`:

```
apiVersion: networking.ironcore.dev/v1alpha1
destinations:
- ip: 192.168.108.0
  targetRef:
    name: balpert-vip-nic
    providerID: ironcore-net://ironcore-net-system/0e5f0289-bab9-5849-a233-ace6d196e79a/ironcore1-vm1.ironcore1-vm1-n1/bec871e3-fb5e-4768-8ffe-2e5f857ba2ef
kind: LoadBalancerRouting
metadata:
  name: balpert-test-lb
  namespace: balpert
networkRef:
  name: test-vip-network
```

The apinetlet should create an api-net `Loadbalancer` like this:

```
apiVersion: core.apinet.ironcore.dev/v1alpha1
kind: LoadBalancer
metadata:
  creationTimestamp: "2025-05-16T21:10:24Z"
  labels:
    apinetlet.ironcore.dev/loadbalancer-name: balpert-test-lb
    apinetlet.ironcore.dev/loadbalancer-namespace: balpert
  name: bfa84d3e-a11e-4423-9c3c-046f9fc035ef
  namespace: ironcore-net-system
spec:
  ips:
  - ip: 160.44.67.112
    ipFamily: IPv4
    name: ipv4
  networkRef:
    name: 31f9c132-cdd7-4f2e-be8f-ed1ebc533e43
  ports:
  - port: 80
    protocol: TCP
  selector:
    matchLabels:
      apinetlet.ironcore.dev/loadbalancer-name: balpert-test-lb
      apinetlet.ironcore.dev/loadbalancer-namespace: balpert
      apinetlet.ironcore.dev/loadbalancer-uid: bfa84d3e-a11e-4423-9c3c-046f9fc035ef
  template:
    metadata:
      creationTimestamp: null
      labels:
        apinetlet.ironcore.dev/loadbalancer-name: balpert-test-lb
        apinetlet.ironcore.dev/loadbalancer-namespace: balpert
        apinetlet.ironcore.dev/loadbalancer-uid: bfa84d3e-a11e-4423-9c3c-046f9fc035ef
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms: 
            - matchFields:
              - key: "metadata.name"
                operator: In
                values:
                - "ironcore1-vm1.ironcore1-vm1-n1"
        instanceAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                apinetlet.ironcore.dev/loadbalancer-name: balpert-test-lb
                apinetlet.ironcore.dev/loadbalancer-namespace: balpert
                apinetlet.ironcore.dev/loadbalancer-uid: bfa84d3e-a11e-4423-9c3c-046f9fc035ef
            topologyKey: topology.core.apinet.ironcore.dev/zone
      loadBalancerType: ""
      networkRef: {}
      type: ""
  type: Public
status: {}
```

The newly added part in this example is 

```
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms: 
            - matchFields:
              - key: "metadata.name"
                operator: In
                values:
                - "ironcore1-vm1.ironcore1-vm1-n1"
```

## Motivation

This behavioral change ensures that metalnet loadbalancers will be materialized only on machinepools which also host machines that are eligible targets for a loadbalancer.
